version: "3"

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    restart: on-failure:5
    depends_on:
      - uwsgi
      - db
    environment:
      - DEBUG=True
      - DATABASE_SETTINGS_MODULE=django_project.settings
    volumes:
      - ../django_project:/django_project/
      - ../static:/home/web/static:rw
      - ../media:/home/web/media:rw

  db:
    container_name: maps-postgres-db
    image: kartoza/postgis:9.6-2.4
    volumes:
      - ./backups:/backups
      - ./sql:/sql
    environment:
      - POSTGRES_USER=maps
      - POSTGRES_PASSWORD=maps
      - POSTGRES_DB=maps
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      backend:
        aliases:
          - db

  redis:
    image: redis:6
    container_name: maps-redis-cache
    restart: unless-stopped
    networks:
      - backend

  uwsgi:
    # Note you cannot scale if you use container_name
    &uwsgi
    container_name: maps-uwsgi
    build:
      context: ./docker
      dockerfile: Dockerfile
    hostname: uwsgi
    links:
      - redis:redis
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=django_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ../django_project:/home/web/django_project
      - ./static:/home/web/static:rw
      - ./media:/home/web/media:rw
      - ./reports:/home/web/reports
      - ./logs:/var/log/
    restart: on-failure:5
    user: root
    networks:
      backend:
        aliases:
          - uwsgi

    # worker:
    #   <<: *uwsgi
    #   build: docker
    #   hostname: worker
    #   container_name: maps-worker
    #   command: celery -A django_project.celery worker -l INFO

    #   volumes:
    #     - ../django_project:/home/web/django_project:rw
    #     - ./static:/home/web/static:rw
    #     - ./media:/home/web/media:rw
    #     - ./reports:/home/web/maps/reports
    #     - ./logs:/var/log/
    #   restart: on-failure:5
    #   depends_on:
    #     - redis
    #     - uwsgi
    #   networks:
    #     backend:
    #       aliases:
    #         - backend

networks:
  backend:
